MyMvcAppFinal/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using MyMvcAppFinal.Data;
using MyMvcAppFinal.Models;
using MyMvcAppFinal.Models.DTO;
using MyMvcAppFinal.Services;

namespace MyMvcAppFinal.Controllers
{
    public class UnitController : Controller
    {
       
        private IUnitService _unitService;
        public UnitController(UnitContext context, IUnitService unitService)
        {
            _unitService = unitService;
        }

       
        public async Task<IActionResult> Synchronize()
        {
            try
            {
                var path = Path.Combine(Environment.CurrentDirectory, "data.json");
                var jsonData = System.IO.File.ReadAllText(path);
                var localUnits = Newtonsoft.Json.JsonConvert.DeserializeObject<DeserializeUnitListDto>(jsonData)?.Units;
                if (localUnits != null)
                {
                    await _unitService.Synchronize(localUnits);
                }
            } catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            

            return RedirectToAction("Index");
        }

        // GET: Units
        public async Task<IActionResult> Index()
        {
            return View(await _unitService.Index());
        }

        // GET: Units/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _unitService.Units() == null)
            {
                return NotFound();
            }

            var unit = await _unitService.Details((int)id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // GET: Units/Create
        public IActionResult Create()
        {
            ViewData["ParentId"] = new SelectList(_unitService.Units(), "Id", "Name");
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ParentId")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                await _unitService.Create(unit);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_unitService.Units(), "Id", "Name", unit.ParentId);
            return View(unit);
        }

        // GET: Units/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _unitService.Units() == null)
            {
                return NotFound();
            }

            var unit = await _unitService.GetUnitById((int)id);
            if (unit == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_unitService.Units(), "Id", "Name", unit.ParentId);
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ParentId")] Unit unit)
        {
            if (id != unit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {                  
                    await _unitService.Edit(unit);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitExists(unit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_unitService.Units(), "Id", "Name", unit.ParentId);
            return View(unit);
        }

        // GET: Units/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _unitService.Units() == null)
            {
                return NotFound();
            }

            var unit = await _unitService.Details((int)id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_unitService.Units() == null)
            {
                return Problem("Entity set 'UnitContext.Units'  is null.");
            }
            var unit = await _unitService.GetUnitById(id);
            if (unit != null)
            {
                await _unitService.DeleteConfirmed(unit);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool UnitExists(int id)
        {
            return _unitService.UnitExists(id);
        }
    }
}

MyMvcAppFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyMvcAppFinal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Unit" asp-action="Index">MyMvcAppFinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Unit" asp-action="Index">Подразделения</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyMvcAppFinal - <a asp-area="" asp-controller="Unit" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>